<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <?php echo $this->getChild('head')->toHtml()?>
</head>

<body>
    <pre>
    <div><?php echo $this->getChild('header')->toHtml()?></div>
    <div><?php echo $this->getChild('footer')->toHtml()?></div>
    <div><?php echo $this->getChild('messages')->toHtml()?></div>
    <div><?php echo $this->getChild('content')->toHtml()?></div>
    <div><?php echo $this->getChild('left')->toHtml()?></div>
    <!-- <div>Content</div>
    <div>Footer</div> -->
</body>

</html>