<?php $banners = $this->getData('banners'); ?>
<div class="banner-list-container">
    <div style="display: flex;justify-content: space-between;align-items: center">
        <a href="<?php echo $this->getUrl('admin/banner/form') ?>">
            <button class="add-btn">
                + Add New Banner
            </button>
        </a>
    </div>
    <div class="banner-grid-container" >
        <?php foreach ($banners as $banner): ?>
            <div class="banner-wrapper">
                <div style="position: absolute">
                    <a
                        href="<?php echo $this->getUrl('admin/banner/form?id=' . $banner->getBanner_id()); ?>">
                        <button class="btn-update">Update</button>
                    </a>
                    <a
                        href="<?php echo $this->getUrl('admin/banner/delete?id=' . $banner->getBanner_id()); ?>">
                        <button class="btn-delete">Delete</button>
                    </a>
                </div>
                <div class="banner-image-wrapper">
                    <img src="<?php echo Mage::getBaseUrl('media/banner/' . $banner->getBanner_image()); ?>" 
                    style="width: 100%;height: 100%;object-fit: contain" alt="No Image">
                </div>
                <p style="display: flex;justify-content: space-between">
                    <span>Status:
                        <?php echo ($banner->getStatus()==1)?'Active':'Inactive'; ?>
                    </span>
                    <span>Display on:
                        <?php echo $banner->getShow_on(); ?>
                    </span>
                </p>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<style>
    .banner-list-container {
        font-family: Arial, sans-serif;
    }

    .banner-list-container .add-btn {
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
    }

    .banner-list-container .add-btn:hover {
        background-color: #0056b3;
    }

    .banner-grid-container {
        margin: 10px;
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(25%, 1fr));
        gap: 10px;
        box-sizing: border-box;
    }

    .banner-wrapper {
        width: 100%;
        padding: 10px;
        background: white;
        position: relative;
        box-sizing: border-box;
    }

    .banner-wrapper .btn-update,
    .banner-wrapper .btn-delete {
        padding: 5px 10px;
        margin-right: 5px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
        transition: background-color .3s ease;
    }

    .banner-wrapper .btn-delete {
        background-color: #dc3545;
    }

    .banner-wrapper .btn-update:hover,
    .banner-wrapper .btn-delete:hover {
        background-color: #0056b3;
    }

    .banner-image-wrapper {
        width: 100%;
        height: 200px;
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>