<footer>
    <div class="footer-top">
        <p style="color: white;margin: 10px 0;">Contact Us</p>
        <p>
            <i class="fa-solid fa-phone" style="color: #ffffff;"></i>
            <a href="tel:+919558811276">+91 9558811276</a>
        </p>
        <p>
            <i class="fa-regular fa-envelope" style="color: #ffffff;"></i>
            <a href="mailto:tankdhruvik29@gmail.com">tankdhruvik29@gmail.com</a>
        </p>
        <p>
            <i class="fa-solid fa-location-pin" style="color: #ffffff;"></i>
            <a href="">Ahmedabad, Gujarat 382350</a>
        </p>
    </div>
    <div class="footer-bottom">
        <p>@2024 DhruvikTank All Rights Reserved.</p>
        <div>
            <a href="#">Terms of Service</a>
            <a href="#">Privacy Policy</a>
        </div>
    </div>
</footer>