<?php $customer = ($this->getData('customer') == '') ? false : $this->getData('customer'); ?>
<header>
    <div style="display: flex;gap: 10px;">
        <div class="logo-container">
            <a href="<?php echo Mage::getBaseUrl('') ?>" style="height: fit-content;display: block;">
                <img style="padding: 0;" src="<?php echo Mage::getBaseUrl('skin/images/logo-white.png') ?>"
                    height="35px" alt="">
            </a>
        </div>
        <div class="input-search">
            <i class="fa-solid fa-magnifying-glass"></i>
            <input type="search" name="" placeholder="Search For Products" id="">
        </div>
    </div>
    <div style="display: flex;gap: 10px;">
        <div class="header-btn login">
            <a href="<?php echo (!$customer) ? Mage::getBaseUrl('customer/account/login') : '#'; ?>"
                class="login-btn-txt" style="color: white;font-weight: 500;">
                <span>
                    <?php echo (!$customer) ? 'Login' : $customer->getFirst_name(); ?>
                </span>
                <i class="fa-solid fa-angle-down" style="font-size: 12px;"></i>
            </a>
            <div class="login-options">
                <ul style="width: 150px">
                    <li>
                        <a href="<?php echo Mage::getBaseUrl('customer/account/dashboard') ?>">
                            <i class="fa-regular fa-circle-user"></i>My Profile
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getBaseUrl('order') ?>">
                            <i class="fa-solid fa-boxes-stacked"></i>Orders
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo Mage::getBaseUrl('customer/account/logout') ?>">
                            <i class="fa-solid fa-arrow-right-from-bracket"></i>Log Out
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="header-btn">
            <a href="<?php echo Mage::getBaseUrl('cart') ?>" style="color: white" class="cart-btn-txt">
                <i class="fa-solid fa-cart-shopping"></i>
                <span>Cart</span>
            </a>
        </div>
    </div>

</header>