<?php $js = $this->getJs(); ?>
<?php if (count($js)): ?>
    <?php foreach ($js as $_js): ?>
        <script src="<?php echo $this->getJsUrl($_js); ?>"></script>
    <?php endforeach; ?>
<?php endif; ?>
<?php $css = $this->getCss(); ?>
<?php if (count($css)): ?>
    <?php foreach ($css as $_css): ?>
        <link rel="stylesheet" href="<?php echo $this->getCssUrl($_css); ?>">
    <?php endforeach; ?>
<?php endif; ?>