
<header class="main-header">
    <div class="logo">
      <img src="<?php echo Mage::getBaseUrl('skin/img/logo.png')?>" alt="Ecommerce Logo">
    </div>
    <nav class="main-nav">
      <ul>
        <li><a href="http://localhost/practise/mvc_project/page/index/index">Home </a></li>
        <li><a href="http://localhost/practise/mvc_project/admin/catalog_product/form">Product Form </a></li>
        <li><a href="http://localhost/practise/mvc_project/admin/catalog_product/list">Product List</a></li>
        <li><a href="http://localhost/practise/mvc_project/admin/catalog_category/form">Category Form </a></li>
        <li><a href="http://localhost/practise/mvc_project/admin/catalog_category/list">Category List</a></li>
      </ul>
    </nav>
  </header>
