<div class="admin-login-container">
    <form action="<?php echo Mage::getBaseUrl('admin/user/login') ?>" method="post">
        <div>
            <label for="email">Email</label>
            <input type="email" name="adminlogin[email]" id="email">
        </div>
        <div>
            <label for="password">Password</label>
            <input type="password" name="adminlogin[password]" id="password">
        </div>
        <div>
            <input type="submit" value="Login">
        </div>
    </form>
</div>