<?php
$category = $this->getData();
?>
<div class="form-container" style="width: 60%;margin: 10px auto">
    <h1>Category Form</h1>
    <form action="<?php echo $this->getUrl('admin/catalog_category/save'); ?>" method="post">
        <input type="hidden" name="category[category_id]" value="<?php echo $category->getCategory_id() ?>">
        <div>
            <label for="cat_name" style="display: block;">Category Name</label>
            <input type="text" name="category[category_name]" value="<?php echo $category->getCategory_name() ?>" id="cat_name">
        </div>
        <?php echo $this->getRenderer("text", ["name"=>"category[category]", "id"=>"safd"]); ?>
        <div>
            Status:<br>
            <input type="radio" value="1" name="category[status]" id="active"><label for="active"
                style="display: inline;margin: 0 10px;">Active</label>
            <input type="radio" value="0" name="category[status]" id="inactive"><label for="inactive"
                style="display: inline;margin: 0 10px;">Inactive</label>
        </div>
        <input type="submit" value="Submit">
    </form>
</div>