<?php
$categoryCollection = Mage::getModel('catalog/category')->getCollection();
$categories = $categoryCollection->getData();
?>
<div class="table" style="width: fit-content;">
    <h2>Category List</h2>
    <table>
        <tr>
            <th>Category Id</th>
            <th>Category Name</th>
            <th>Status</th>
            <th></th>
            <th></th>
        </tr>
        <?php foreach ($categories as $category): ?>
            <tr>
                <td>
                    <?php echo $category->getCategory_id(); ?>
                </td>
                <td>
                    <?php echo $category->getCategory_name(); ?>
                </td>
                <td>
                    <?php echo ($category->getStatus() == 1) ? 'active' : 'inactive'; ?>
                </td>
                <td>
                    <a
                        href="<?php echo $this->getUrl('admin/catalog_category/form?id=' . $category->getCategory_id()) ?>">
                        <button>Edit</button>
                    </a>
                </td>
                <td>
                    <a
                        href="<?php echo $this->getUrl('admin/catalog_category/delete?id=' . $category->getCategory_id()) ?>">
                        <button>Remove</button>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>