<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <?php echo ($this->getChild('head')->toHtml())?>
</head>
<body>
    
   
    <section class="container_content"><?php echo ($this->getChildHtml('header'))?></section>
    <section class="container_content"><?php echo ($this->getChildHtml('content'))?></section>
    <section class="container_content"><?php echo ($this->getChildHtml('footer'))?></section>
    
    
</body>
</html>