<?php $js = $this->getJs(); ?>
<?php if (count($js) > 0):?>
    <?php foreach($js as $_js):?>
        <script type="" src="<?php echo $_js;?>"></script>
    <?php endforeach;?>
<?php endif;?>

<?php $css = $this->getCss(); ?>
<?php if (count($css) > 0):?>
    <?php foreach($css as $_css):?>
        <!-- <link rel="stylesheet" href="<?php echo $_css?>"> -->
        <style src="<?php echo $_css?>"></style>
    <?php endforeach;?>
<?php endif;?>

