<div class="form-container">
    <form action="<?php echo Mage::getBaseUrl("admin/import/upload") ?>" onsubmit="return validateData()" name="contactForm" method="post" enctype="multipart/form-data">
        <div>
            <label for="file">CSV File</label>
            <input type="file" name="csvfile" id="file">
        </div>
        <div>
            <input type="submit" value="Upload">
        </div>
    </form>
</div>
<script>
    function validateData(){
        return true;
    }
</script>