<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <?php echo ($this->getChild('head')->toHtml())?>
</head>
<body>
    
<div class="mainCont">
    <section class="left2"><?php echo ($this->getChildHtml('adminleft'))?></section>
    <section class="container_content"><?php echo ($this->getChildHtml('content'))?></section>
</div>

    
</body>
</html>