<?php $converterModel = Mage::getModel('currency/converter')->getCollection(); ?>
<?php $catModel = Mage::getModel('currency/rate')->getCollection(); ?>
<?php $currModel = Mage::getModel('currency/rate')->getCollection(); ?>

<section class="list">
    <h2>List</h2>
    <table border="1">
        <tr>
            <th>Id</th>
            <!-- <th>User Name</th> -->
            <th>Amount</th>
            <th>Country</th>
            <th>Current_Country</th>
            <th>Result</th>
            <th>Delete</th>
        </tr>
        <?php foreach ($converterModel->getData() as $converter): ?>
            <!-- <tr> -->
            <tr id="row_<?= $converter->getId() ?>">
                <td style="width:30px">
                    <?= $converter->getId() ?>
                </td>
                <!-- <td>
                    <?= $converter->getUserName() ?>
                </td> -->
                <td>
                    <?= $converter->getAmount() ?>
                </td>
                <td>
                    <?php
                    foreach ($catModel->getData() as $rate) {
                        if ($rate->getId() == $converter->getCountry()) {
                            $country = $rate->getCountry();
                            break;
                        }
                    }
                    echo $country;
                    ?>
                </td>
                <td>
                    <?php
                    foreach ($currModel->getData() as $rate) {
                        if ($rate->getId() == $converter->getCurrencyCountry()) {
                            $country = $rate->getCountry();
                            break;
                        }
                    }
                    echo $country;
                    ?>
                </td>
                <td> <?php 
                    foreach ($catModel->getData() as $rate) {
                        if ($rate->getId() == $converter->getCountry()) {
                            $conv = $rate->getRate();
                            break;
                        }
                    }
                    foreach ($currModel->getData() as $rate) {
                        if ($rate->getId() == $converter->getCurrencyCountry()) {
                            $curConv = $rate->getRate();
                            break;
                        }
                    }
                    // echo $conv; 
                    // echo $curConv; 
                    echo (($converter->getAmount())/$conv * $curConv);

                    ?>
                </td>
                <td><a
                        href="http://localhost/practise/mvc_project/admin/currency_converter/delete?id=<?= $converter->getId() ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

</section>