<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <?php echo ($this->getChild('head')->toHtml())?>
</head>
<body>
    
    <?php echo ($this->getChildHtml('header'))?>
    <section class="container_content"><?php echo ($this->getChildHtml('content'))?></section>
    <?php echo ($this->getChildHtml('footer'))?>
    
</body>
</html>