<?php
$categories = Mage::getModel('catalog/category')->getCollection()->getData();
$product = $this->getData();
?>
<div class="form-container">
    <div style="background: rgb(39, 39, 255);color:white;height: 70px">
        <p style="font-size: 16px;font-weight: 600">Product</p>
    </div>
    <div class="form">
        <p style="border-bottom: 1px solid black;padding: 10px 0;font-weight: 600;">
            <?php if ($product->getProduct_id() != ''): ?>
                Product Id -
                <?php echo $product->getProduct_id(); ?>
            <?php else: ?>
                New Product
            <?php endif; ?>
        </p>
        <form action="<?php echo $this->getUrl('admin/catalog_product/save'); ?>" name="product-form" method="post"
            enctype="multipart/form-data">
            <input type="hidden" name="product[product_id]" value="<?php echo $product->getProduct_id(); ?>">
            <div class="row">
                <div>
                    <label for="name">Name</label>
                    <input type="text" name="product[name]" value="<?php echo $product->getname(); ?>" id="name">
                    <p name="nameError">Error</p>
                </div>
                <div>
                    <label for="sku">SKU</label>
                    <?php echo $this->getRenderer("text", ["name" => "product[sku]", "value" => $product->getSku(), "id" => "sku"]) ?>
                </div>
            </div>
            <div class="row">
                <div>
                    <label for="color">Color:</label>
                    <input type="text" name="product[color]" value="<?php echo $product->getcolor() ?>" id="color">
                </div>
                <div>
                    <label for="size">Size:</label>
                    <input type="text" name="product[size]" value="<?php echo $product->getsize() ?>" id="size">
                </div>
            </div>
            <div>
                <label for="desc">Description:</label>
                <textarea name="product[description]" id="desc" cols="30"
                    rows="2"><?php echo $product->getdescription() ?></textarea>
            </div>
            <div class="row">
                <div>
                    <label for="img-link">Image Link:</label>
                    <input type="file" name="image_link" id="img-link">
                </div>
                <div>
                    <label for="link">Link:</label>
                    <input type="url" name="product[link]" value="<?php echo $product->getLink() ?>" id="link">
                </div>
            </div>
            <div class="row">
                <div>
                    <label for="cat">Category:</label>
                    <?php echo $this->getRenderer("select", ["name" => "product[category_id]", "id" => "cat", "options" => Mage::getModel('catalog/category')->getCategoryArray(), "selected" => $product->getCategory_id()]) ?>
                </div>
                <div>
                    <label for="price">Price:</label>
                    <input type="text" name="product[price]" value="<?php echo $product->getPrice(); ?>"
                        onkeyup="calculateMargin()" id="price">
                </div>
            </div>
            <div class="row">
                <div>
                    <label for="mfr-cost">Manufacturer Cost</label>
                    <input type="text" name="product[mfr_cost]" value="<?php echo $product->getMfr_cost(); ?>"
                        onkeyup="calculateTotal()" id="mfr-cost">
                </div>
                <div>
                    <label for="shipping-cost">Shipping Cost</label>
                    <input type="text" name="product[shipping_cost]" value="<?php echo $product->getShipping_cost(); ?>"
                        onkeyup="calculateTotal()" id="shipping-cost">
                </div>
                <div>
                    <label for="total-cost">Total Cost</label>
                    <input type="text" name="product[total_cost]" value="<?php echo $product->getTotal_cost(); ?>"
                        onchange="calculateMargin()" id="total-cost">
                </div>
            </div>
            <div class="row">
                <div>
                    <label for="margin-percentage">Margin Percentage</label>
                    <input type="text" name="product[margin_percentage]"
                        value="<?php echo $product->getMargin_percentage(); ?>" id="margin-percentage">
                </div>
                <div>
                    <label for="min-price">Minimum Price</label>
                    <input type="text" name="product[min_price]" value="<?php echo $product->getMin_price(); ?>"
                        id="min-price">
                </div>
                <div>
                    <label for="status">Status:</label>
                    <?php $status = ($product->getStatus() == 'enabled') ? 1 : 0; ?>

                    <input type="radio" name="product[status]" value="1" <?php echo ($status == 1) ? 'checked' : ''; ?>
                        id="active">
                    <label style="display: inline;" for="active">Active</label>
                    <input type="radio" name="product[status]" value="0" <?php echo ($status == 0) ? 'checked' : ''; ?>
                        id="inactive">
                    <label style="display: inline;" for="inactive">Inactive</label>
                </div>
            </div>
            <div class="button-group" style="margin: 0 auto;width: fit-content;">
                <a class="btn-new" href="/practice_mvc/admin/catalog_product/form"><span><i
                            class="fa-solid fa-plus"></i> New</span></a>
                <button class="btn-save" type="submit" name="submit"><i class="fa-regular fa-floppy-disk"></i>
                    Save</button>
                <a class="btn-cancel" href="/practice_mvc/admin/catalog_product/list"><span><i
                            class="fa-solid fa-xmark"></i> Cancel</span></a>
            </div>
        </form>
    </div>
</div>

<script>
    
</script>