
<header class="main-header">
    <div class="logo">
      <img src="<?php echo Mage::getBaseUrl('skin/images/logo.png')?>" alt="Ecommerce Logo">
     
    </div>
    <nav class="main-nav">
      <ul>
        <li><a>ADMIN PANEL : </a></li>
        <li><a href="<?php echo $this->getUrl('admin/catalog_product/list') ?>">Product List</a></li>
        <li><a href="<?php echo $this->getUrl('admin/catalog_product/form') ?>">Add Product</a></li>
        <li><a href="<?php echo $this->getUrl('admin/catalog_category/list') ?>">Category List</a></li>
        <li><a href="<?php echo $this->getUrl('admin/catalog_category/form') ?>">Add Category</a></li>
        <li><a href="<?php echo $this->getUrl('admin/banner/form') ?>">Add Banner</a></li>
      </ul>
    </nav>
  </header>