<!-- <div class="banner-container" style="
        background: url();
        background-size: contain;
        background-repeat: no-repeat;
        background-position: 80%;
    ">
    <div class="banner-text">
        <p style="margin: 0;padding: 0;color: lightblue;">
            <span style="font-size: 60px;">ONLINE</span>
            <br>
            <span style="font-size: 65px;">Shop</span>
        </p>
    </div>
</div> -->
Banner