<section class="footer">

    <p>Copyright © 2023  |  All rights reserved<br> Designed and Developed by Jinil Prajapati. This website is optimized for modern browsers and mobile devices. For the best experience, please upgrade to the latest version of your preferred browser.</p>
    
    <div class="icons">
      <a href="https://github.com/jinil09/" >Github</a>
      <a href="mailto:jinil.prajapati18@gmail.com" >Mail</a>
      <a href="linkedin.com/in/jinil-prajapati-1831b8220/" >Linkedin</a>

    </div>
    
</section>