<div class="list">
    <h2>Banner List</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>View</th>
                <th>Status</th>
                <th colspan="2">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->getBannerList() as $banner): ?>
                <tr>
                    <td>
                        <?php echo $banner->getBannerPath() ?>
                    </td>
                    <td>
                        <a href="<?php echo $banner->getBannerImage() ?>" target="_blank">View</a>
                    </td>
                    <td>
                        <?php echo $banner->getStatus() ?>
                    </td>
                    <td><a
                            href="<?php echo $this->getUrl("admin/banner/delete?banner_id={$banner->getId()}") ?>">Delete</a>
                    </td>
                    <td><a href="<?php echo $this->getUrl("admin/banner/form?banner_id={$banner->getId()}") ?>">Update</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>